# -*- coding: utf-8 -*-
"""VN30_analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7gMp6Axi6I18BUh89SmrX1fnS61gy8v

# **Phân tích cấu trúc thị trường chứng khoán Việt Nam bằng PCA từ rổ VN30**


---

## **Giới thiệu và Thu thập dữ liệu chứng khoán VN30**

### **Cấu trúc thị trường và Chỉ số VN30**
**VN30 là gì?**
VN30 là chỉ số giá chứng khoán đại diện cho 30 công ty niêm yết trên Sở Giao dịch Chứng khoán TP.HCM (HOSE) có giá trị vốn hóa thị trường và tính thanh khoản cao nhất. Danh mục này được định kỳ xem xét và điều chỉnh để đảm bảo luôn phản ánh đúng các doanh nghiệp đầu ngành.

**Vì sao chọn VN30 để đại diện cho thị trường khi phân tích PCA?**
Trong phân tích cấu trúc thị trường, việc lựa chọn tập dữ liệu đầu vào rất quan trọng:
1. **Tính đại diện cao:** Rổ VN30 thường chiếm khoảng 70-80% tổng giá trị vốn hóa và thanh khoản của toàn sàn HOSE. Do đó, xu hướng của VN30 phản ánh gần như chính xác nhịp đập của toàn thị trường chứng khoán Việt Nam.
2. **Loại bỏ nhiễu (Noise reduction):** Thị trường có hàng trăm mã cổ phiếu nhỏ (penny stocks) với thanh khoản thấp, dễ bị thao túng giá. Việc tập trung vào nhóm Blue-chips (VN30) giúp dữ liệu ổn định, minh bạch và làm tăng độ tin cậy khi trích xuất các thành phần chính bằng thuật toán học máy (PCA).
3. **Tính liên tục của dữ liệu:** 30 mã trong rổ VN30 đều có giao dịch sôi động hàng ngày, giảm thiểu tối đa các giá trị khuyết thiếu (missing values) do mất thanh khoản.

### **Phương pháp thu thập dữ liệu**
Để đảm bảo tính chính xác và sự ổn định tuyệt đối của dữ liệu, nhóm đã quyết định linh hoạt kết hợp hai phương pháp:
- **Đối với 30 mã cổ phiếu VN30:** Sử dụng thư viện `yfinance` kết nối trực tiếp với API công khai của Yahoo Finance để tự động tải về lịch sử giá đóng cửa (Close Price).
- **Đối với chỉ số tham chiếu VN30-Index:** Do các API tài chính trong nước thường có tường lửa chặn truy cập từ máy chủ đám mây (Google Colab), nhóm đã chủ động thu thập thủ công bằng cách tải trực tiếp file dữ liệu lịch sử (CSV) từ nền tảng **Investing.com**.

Việc kết hợp này vừa tận dụng được sức mạnh tự động hóa của API, vừa thể hiện khả năng xử lý tình huống linh hoạt để có được bộ dữ liệu Panel Data hoàn chỉnh nhất đưa vào mô hình.

## **1 Thu thập và tiền xử lý dữ liệu chứng khoán**
"""

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import yfinance as yf
import pandas as pd
from datetime import datetime, timedelta

print("--- ĐANG THU THẬP DỮ LIỆU CHỨNG KHOÁN ---")

# Nguồn dữ liệu và Phương pháp thu thập:
# 1. Dữ liệu giá đóng cửa của 30 cổ phiếu VN30 được thu thập thông qua thư viện 'yfinance' (Yahoo Finance API).
# 2. Dữ liệu chỉ số VN30-Index được đọc từ file CSV 'VN30.csv.csv'.

# 1. Khai báo 30 mã cổ phiếu thuộc rổ VN30
vn30_tickers = [
    'ACB', 'BCM', 'BID', 'BVH', 'CTG', 'FPT', 'GAS', 'GVR', 'HDB', 'HPG',
    'MBB', 'MSN', 'MWG', 'PLX', 'POW', 'SAB', 'SHB', 'SSB', 'SSI', 'STB',
    'TCB', 'TPB', 'VCB', 'VHM', 'VIB', 'VIC', 'VJC', 'VNM', 'VPB', 'VRE'
]
tickers_yf = [ticker + '.VN' for ticker in vn30_tickers]

# Xác định mốc thời gian: 1 năm gần nhất (tính từ 30/04/2026 lùi lại)
start_str = '2025-04-30'
end_str = '2026-04-30'

print(f"Giai đoạn thu thập: {start_str} đến {end_str}")

# 2. Thu thập dữ liệu 30 mã VN30 từ Yahoo Finance API
print("\nĐang tải dữ liệu 30 mã cổ phiếu từ Yahoo Finance...")
panel_data = yf.download(tickers_yf, start=start_str, end=end_str, progress=False)['Close']
# Xóa hậu tố '.VN' trong tên cột
panel_data.columns = [col.replace('.VN', '') for col in panel_data.columns]
# Chuẩn hóa index về mốc ngày (bỏ giờ, phút)
panel_data.index = pd.to_datetime(panel_data.index).tz_localize(None).normalize()

# 3. Đọc dữ liệu VN30-Index từ file CSV
print("Đang đọc dữ liệu VN30-Index từ file VN30.csv.csv...")
vn30_index_data = pd.read_csv('VN30.csv.csv')

# Trích xuất 2 cột "Ngày" và "Lần cuối" (Giá đóng cửa), sau đó đổi tên
vn30_index_data = vn30_index_data[['Ngày', 'Lần cuối']]
vn30_index_data.columns = ['Date', 'VN30_INDEX']

# Loại bỏ dấu phẩy phân cách hàng nghìn và ép kiểu dữ liệu về số thực (float)
vn30_index_data['VN30_INDEX'] = vn30_index_data['VN30_INDEX'].str.replace(',', '').astype(float)

# Chuyển cột Date sang định dạng datetime chuẩn (theo định dạng dd/mm/yyyy của file) và đưa làm Index
vn30_index_data['Date'] = pd.to_datetime(vn30_index_data['Date'], format='%d/%m/%Y')
vn30_index_data.set_index('Date', inplace=True)
vn30_index_data.index = vn30_index_data.index.tz_localize(None).normalize()

print("-> Đã đọc và xử lý file CSV thành công!")

# 4. Merge (Gộp) thành bảng Panel Data chung
df_final = panel_data.join(vn30_index_data, how='outer')

# 5. Lọc đúng giới hạn 1 năm và Xử lý Missing Values
df_final = df_final.loc[start_str:end_str]
missing_before = df_final.isnull().sum().sum()
# Phương pháp Forward Fill lấp đầy giá trị trống bằng giá của ngày giao dịch gần nhất
df_final = df_final.ffill().bfill()
missing_after = df_final.isnull().sum().sum()

print(f"\n--- HOÀN TẤT XỬ LÝ DỮ LIỆU ---")
print(f"Tổng số giá trị thiếu ban đầu: {missing_before}")
print(f"Tổng số giá trị thiếu sau xử lý (ffill): {missing_after}")

print(f"\nKích thước tập dữ liệu Panel Data: {df_final.shape}")
print("5 dòng dữ liệu đầu tiên:")
display(df_final.head())

"""## **2. Tỷ suất sinh lợi hằng ngày**"""

print("Đang tính toán tỷ suất sinh lợi hằng ngày...")
df_returns = df_final.pct_change().dropna()

print("-> Đã tính toán tỷ suất sinh lợi hằng ngày thành công!")
print(f"Kích thước tập dữ liệu Daily Returns: {df_returns.shape}")
print("5 dòng dữ liệu Daily Returns đầu tiên:")
display(df_returns.head())


# Display descriptive statistics of stock returns
print("\nDescriptive Statistics of Stock Returns:")
display(stock_returns_only.describe())

# Check for any remaining missing values in stock returns
print("\nMissing values in Stock Returns:")
print(stock_returns_only.isnull().sum()[stock_returns_only.isnull().sum() > 0])

# Standardize stock returns (mean-centering)
mean_returns = stock_returns_only.mean()
standardized_returns = stock_returns_only - mean_returns

print("\nShape of standardized_returns:", standardized_returns.shape)

"""### **Vì sao dùng Tỷ suất sinh lợi (Return) thay vì Giá đóng cửa (Close Price)?**
Khi áp dụng thuật toán PCA, việc sử dụng Tỷ suất sinh lợi (Daily Return) thay vì Giá đóng cửa tuyệt đối là bắt buộc vì 2 lý do cốt lõi:
1. **Khắc phục chênh lệch quy mô (Scale):** Mức giá của các cổ phiếu trong VN30 rất khác nhau (Ví dụ: FPT > 100k, trong khi VRE chỉ ~20k). Nếu dùng giá đóng cửa, mô hình PCA sẽ bị sai lệch và thiên vị các cổ phiếu có thị giá lớn. Return giúp đưa tất cả về cùng một hệ quy chiếu là phần trăm (%), giúp việc so sánh công bằng hơn.
2. **Đảm bảo tính dừng (Stationarity):** Chuỗi thời gian của giá cổ phiếu mang tính xu hướng (trend) dài hạn và không dừng (non-stationary). Bằng cách tính Return, ta loại bỏ được xu hướng này, biến dữ liệu thành chuỗi dừng tập trung vào biến động cốt lõi hàng ngày, thỏa mãn giả định của các mô hình định lượng.

### **Ý nghĩa của Ma trận tương quan (Correlation Matrix)**
- **Khái niệm:** Ma trận tương quan đo lường mức độ di chuyển cùng chiều hay ngược chiều giữa các cặp cổ phiếu (giá trị chạy từ -1 đến 1).
- **Ý nghĩa trong PCA:** Trong rổ VN30, các cổ phiếu thường có hệ số tương quan dương khá cao với nhau do chúng cùng chịu tác động từ rủi ro hệ thống (Macro/Market Risk). Tính chất tương quan chặt chẽ này chính là **tiền đề quan trọng nhất** để thuật toán PCA có thể gom nhóm và trích xuất ra một "Thành phần chính" (Principal Component 1) giải thích được phần lớn sự biến động chung của toàn thị trường.

## **3 Khám phá EDA**
"""

print("### Thông tin chung về DataFrame df_final ###")
df_final.info()

print("\n### Thống kê mô tả cho df_final ###")
display(df_final.describe())

print("\n### Kiểm tra lại giá trị thiếu trong df_final ###")
missing_values_df_final = df_final.isnull().sum()
print(missing_values_df_final[missing_values_df_final > 0])

print("\n### Thống kê mô tả cho df_returns (Tỷ suất sinh lợi) ###")
display(df_returns.describe())

print("\n### Kiểm tra lại giá trị thiếu trong df_returns ###")
missing_values_df_returns = df_returns.isnull().sum()
print(missing_values_df_returns[missing_values_df_returns > 0])

print("\n### Ma trận tương quan của tỷ suất sinh lợi (df_returns) ###")
correlation_matrix = df_returns.corr()
display(correlation_matrix.head()) # Hiển thị 5 dòng đầu của ma trận tương quan để xem trước

"""**a. Phân phối lợi suất hàng ngày**"""

# Thiết lập kích thước đồ thị
plt.figure(figsize=(20, 25))

# Lặp qua từng cột (từng mã cổ phiếu/chỉ số) trong df_returns để vẽ biểu đồ phân phối
for i, column in enumerate(df_returns.columns):
    plt.subplot(6, 6, i + 1) # Tạo subplot (6 hàng, 6 cột)
    sns.histplot(df_returns[column], kde=True, bins=30, color='skyblue')
    plt.title(f'Phân phối lợi suất {column}')
    plt.xlabel('Lợi suất hàng ngày')
    plt.ylabel('Tần suất')
    plt.grid(True, linestyle='--', alpha=0.6)

plt.tight_layout() # Điều chỉnh layout để tránh chồng chéo tiêu đề
plt.suptitle('Phân phối lợi suất hàng ngày của VN30 và VN30-Index', y=1.02, fontsize=16)
plt.show()

"""**b. Ma trận tương quan của lợi suất**"""

print("### 3.2. Ma trận tương quan của lợi suất chuẩn hóa ###")

# Chuẩn hóa lợi suất bằng StandardScaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
standardized_returns = pd.DataFrame(scaler.fit_transform(df_returns), columns=df_returns.columns, index=df_returns.index)

# Tính toán ma trận tương quan của lợi suất chuẩn hóa
correlation_matrix_standardized = standardized_returns.corr()

# Trực quan hóa ma trận tương quan bằng heatmap
plt.figure(figsize=(18, 16))
sns.heatmap(correlation_matrix_standardized, annot=False, cmap='coolwarm', fmt=".2f", linewidths=.5)
plt.title('Ma trận tương quan của lợi suất hàng ngày đã chuẩn hóa (Standardized Daily Returns Correlation Matrix)')
plt.xlabel('Mã cổ phiếu')
plt.ylabel('Mã cổ phiếu')
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

print("\nMa trận tương quan (5x5 đầu tiên) của lợi suất chuẩn hóa:")
display(correlation_matrix_standardized.iloc[:5, :5])

"""## **4. Xây dựng thuật toán PCA**

### **a. Tính toán ma trận hiệp phương sai (Covariance Matrix)**
"""

# Calculate the covariance matrix
cov_matrix = standardized_returns.cov()

print("Shape of covariance matrix:", cov_matrix.shape)
print("\nCovariance Matrix (first 5x5):")
display(cov_matrix.iloc[:5, :5])

"""### **b. Tính toán trị riêng (Eigenvalues) và vector riêng (Eigenvectors)**"""

# Ensure standardized_stock_returns is defined and correctly structured
# This block is added for robustness in case previous cells were not run
if 'standardized_stock_returns' not in globals():
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Assuming df_returns is defined from previous cells
    # standardized_returns includes VN30_INDEX
    temp_standardized_returns = pd.DataFrame(scaler.fit_transform(df_returns), columns=df_returns.columns, index=df_returns.index)
    # standardized_stock_returns EXCLUDES VN30_INDEX
    standardized_stock_returns = temp_standardized_returns.drop(columns=['VN30_INDEX'], errors='ignore')

X = standardized_stock_returns.values # Lấy giá trị numpy array từ DataFrame đã chuẩn hóa chỉ chứa cổ phiếu

print(f"Kích thước dữ liệu đầu vào cho PCA: {X.shape}")
print(f"Giá trị trung bình của cột đầu tiên sau chuẩn hóa (kiểm tra): {np.mean(X[:,0]):.4f}")

cov_matrix = np.cov(X, rowvar=False) # rowvar=False vì mỗi hàng là một quan sát, mỗi cột là một biến

print(f"\nKích thước ma trận hiệp phương sai: {cov_matrix.shape}")

# Tính trị riêng (eigenvalues) và vector riêng (eigenvectors) từ ma trận hiệp phương sai.
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("\nĐã tính toán trị riêng và vector riêng.")

"""**Giải thích ý nghĩa của các vector riêng trong PCA**

**1. Hướng của Phương sai tối đa:** Mỗi vector riêng đại diện cho một hướng trong không gian dữ liệu mà dọc theo đó dữ liệu có phương sai lớn nhất. Hay nói cách khác, chúng chỉ ra các hướng mà dữ liệu 'trải rộng' nhiều nhất.

**2. Độc lập và Trực giao:** Các vector riêng này là trực giao (vuông góc) với nhau, có nghĩa là mỗi thành phần chính nắm bắt một khía cạnh biến động độc lập của dữ liệu.

**3. Tầm quan trọng:** Vector riêng tương ứng với trị riêng (eigenvalue) càng lớn thì nó càng giải thích được nhiều phương sai của dữ liệu. Do đó, vector riêng có trị riêng lớn nhất chính là PC1 (thành phần chính đầu tiên), vector có trị riêng lớn thứ hai là PC2, và cứ thế tiếp tục.

**4. Hệ số tải (Loadings):** Các giá trị thành phần trong mỗi vector riêng (còn gọi là 'loadings') cho biết mức độ đóng góp của từng biến gốc (ví dụ: từng mã cổ phiếu trong trường hợp này) vào thành phần chính đó. Một loading lớn (dương hoặc âm) cho thấy biến gốc đó có ảnh hưởng mạnh đến hướng và biến động của thành phần chính.

### **c. Sắp xếp các thành phần chính**
"""

idx = np.argsort(eigenvalues)[::-1] # Lấy chỉ số để sắp xếp giảm dần
sorted_eigenvalues = eigenvalues[idx]
sorted_eigenvectors = eigenvectors[:, idx]

print("\nTrị riêng (Eigenvalues) đã sắp xếp:")
print(sorted_eigenvalues)

print("\nVector riêng (Eigenvectors) đã sắp xếp (5 hàng đầu tiên của PC1):")
print(sorted_eigenvectors[:5, :5]) # In 5 hàng đầu của 5 PC đầu tiên

# Tính toán tỷ lệ phương sai giải thích được (Explained Variance Ratio)
explained_variance_ratio = sorted_eigenvalues / np.sum(sorted_eigenvalues)

print("\nExplained Variance Ratio của từng thành phần chính:")
print(explained_variance_ratio)
print(f"\nTổng phương sai được giải thích bởi 2 PC đầu tiên: {explained_variance_ratio[:2].sum()*100:.2f}%")

print("\n--- HOÀN TẤT XÂY DỰNG PCA ---")

# Tạo PC1 (chuỗi thời gian của PC1 scores)
pc1_vector_scratch = sorted_eigenvectors[:, 0] # PC1 là vector riêng đầu tiên

# Chuyển đổi dữ liệu gốc X lên không gian PC1
pc1_scores_scratch = X.dot(pc1_vector_scratch)

# Ensure standardized_stock_returns is defined (for robustness)
if 'standardized_stock_returns' not in globals():
    from sklearn.preprocessing import StandardScaler
    scaler = StandardScaler()
    # Assuming df_returns is defined from previous cells
    temp_standardized_returns = pd.DataFrame(scaler.fit_transform(df_returns), columns=df_returns.columns, index=df_returns.index)
    standardized_stock_returns = temp_standardized_returns.drop(columns=['VN30_INDEX'], errors='ignore')

# Tạo DataFrame cho PC1 scores để dễ dàng sử dụng cho các bước tiếp theo
pc1_index_scratch = pd.Series(pc1_scores_scratch, index=standardized_stock_returns.index, name='PC1_Score')

"""### **c. Phân tích kết quả PCA (Từ thuật toán tự xây dựng)**

**1. Kích thước dữ liệu đầu vào và Ma trận hiệp phương sai:**
*   Dữ liệu đầu vào cho PCA có kích thước `(247, 31)`, tức là 247 ngày giao dịch và 31 biến (30 cổ phiếu + VN30 Index).
*   Ma trận hiệp phương sai có kích thước `(31, 31)`, đúng như mong đợi, cho thấy sự tương quan của 31 biến với chính nó và các biến khác.

**2. Trị riêng (Eigenvalues):**
*   Các trị riêng đã được sắp xếp theo thứ tự giảm dần. Trị riêng càng lớn thì thành phần chính (Principal Component) tương ứng giải thích càng nhiều phương sai trong dữ liệu.
*   PC1 có trị riêng lớn nhất (`12.2596`), PC2 (`2.9293`), PC3 (`2.0557`), v.v. Điều này khẳng định rằng PC1 là thành phần quan trọng nhất, nắm giữ phần lớn thông tin về sự biến động của thị trường.

**3. Vector riêng (Eigenvectors):**
*   Mỗi vector riêng đại diện cho một thành phần chính. Các giá trị trong vector riêng (hay còn gọi là loadings) cho biết mức độ đóng góp của từng cổ phiếu vào thành phần chính đó.
*   Ví dụ, nhìn vào 5 hàng đầu tiên của PC1 (`[-0.2258, -0.1555, -0.1888, -0.1493, -0.2218]`), chúng ta có thể thấy các cổ phiếu tương ứng đang có trọng số âm vào PC1 (mặc dù dấu có thể đảo ngược mà không thay đổi ý nghĩa, quan trọng là giá trị tương đối).

**4. Tỷ lệ phương sai được giải thích (Explained Variance Ratio):**
*   PC1 giải thích gần **39.39%** tổng phương sai của dữ liệu. Đây là một con số đáng kể, cho thấy PC1 đại diện cho một yếu tố chung mạnh mẽ ảnh hưởng đến tất cả các cổ phiếu.
*   Hai thành phần chính đầu tiên (PC1 và PC2) cùng nhau giải thích **48.80%** tổng phương sai. Điều này có nghĩa là gần một nửa sự biến động của 31 cổ phiếu có thể được giải thích chỉ bằng 2 yếu tố chính.
*   Các thành phần sau đó giải thích tỷ lệ phương sai giảm dần, cho thấy chúng đại diện cho các yếu tố biến động nhỏ hơn hoặc đặc thù hơn.

**Kết luận:**
Việc xây dựng PCA từ đầu đã cho thấy rằng một số ít các thành phần chính có thể giải thích một phần lớn sự biến động của thị trường chứng khoán VN30. Đặc biệt, **PC1 nổi lên như một yếu tố thị trường chung (Market Factor)** mạnh mẽ, ảnh hưởng đồng thời đến hầu hết các cổ phiếu. Khả năng nén thông tin này rất hữu ích cho việc phân tích rủi ro, quản lý danh mục và hiểu cấu trúc thị trường.
"""

# Visualize the explained variance ratio (Scree Plot)
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(explained_variance_ratio) + 1), explained_variance_ratio, marker='o', linestyle='--', color='blue')
plt.title('Scree Plot: Explained Variance Ratio per Principal Component')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.grid(True)
plt.xticks(range(1, len(explained_variance_ratio) + 1))
plt.show()

# Calculate cumulative explained variance
cumulative_explained_variance = np.cumsum(explained_variance_ratio)

# Visualize cumulative explained variance
plt.figure(figsize=(10, 6))
plt.plot(range(1, len(cumulative_explained_variance) + 1), cumulative_explained_variance, marker='o', linestyle='-', color='red')
plt.title('Cumulative Explained Variance by Principal Components')
plt.xlabel('Number of Principal Components')
plt.ylabel('Cumulative Explained Variance Ratio')
plt.grid(True)
plt.xticks(range(1, len(cumulative_explained_variance) + 1))
plt.axhline(y=0.95, color='gray', linestyle='--', label='95% threshold')
plt.legend()
plt.show()

"""# **5. Phân tích và trực quan hóa thành phần chính đầu tiên (PC1)**"""

# Chúng ta sẽ sử dụng trực tiếp biến này và đổi tên cho phù hợp với yêu cầu.
PC1_index = pc1_index_scratch

print("--- Chuỗi thời gian của Thành phần chính 1 (PC1_index) ---")
print("5 dòng dữ liệu đầu tiên của PC1_index:")
display(PC1_index.head())

# 2. Trực quan hóa chuỗi thời gian của PC1_index
plt.figure(figsize=(14, 7))
plt.plot(PC1_index.index, PC1_index.values, linestyle='-', color='teal', linewidth=1)
plt.title('Chuỗi thời gian của Thành phần chính 1 (PC1_index)', fontsize=16, fontweight='bold', pad=20)
plt.xlabel('Ngày', fontsize=12)
plt.ylabel('Giá trị PC1', fontsize=12)
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

print("\nPC1 là thành phần chính đầu tiên, đại diện cho phần lớn phương sai trong dữ liệu tỷ suất sinh lợi của các cổ phiếu VN30. Nó thường được hiểu là 'yếu tố thị trường chung' (Market Factor) vì nó nắm bắt xu hướng biến động đồng thời của các mã cổ phiếu trong rổ.")

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

print("--- PC1 Score Chain (first 5 rows) ---")
display(PC1_index.head())

print("\n--- Comparing PC1 and VN30 Index ---")

# 1. Lấy chuỗi lợi suất của VN30_INDEX
vn30_returns = df_returns['VN30_INDEX']

# 2. Sử dụng PC1_index đã được tạo ra (aliased from pc1_index_scratch)
pc1_returns_series = PC1_index # PC1_index already contains the PC1 scores

# 3. Điều chỉnh dấu nếu cần (cho dễ so sánh)
# Tính toán tương quan ban đầu
initial_correlation = np.corrcoef(pc1_returns_series, vn30_returns)[0, 1]

# If correlation is negative, invert the sign of PC1 to align with VN30_INDEX
if initial_correlation < 0:
    pc1_returns_series = -pc1_returns_series
    print(f"  Adjusted PC1_index sign to align with VN30_INDEX (initial correlation: {initial_correlation:.4f})")

# 4. Tính toán Cumulative return (using cumsum for small returns to avoid overflow issues with cumprod)
pc1_cum = pc1_returns_series.cumsum()
vn30_cum = vn30_returns.cumsum()

# 5. Chuẩn hóa 2 đường về cùng thang đo (Scale) để lên biểu đồ đẹp nhất
pc1_cum_scaled = (pc1_cum - pc1_cum.mean()) / pc1_cum.std()
vn30_cum_scaled = (vn30_cum - vn30_cum.mean()) / vn30_cum.std()

# 6. Vẽ biểu đồ so sánh
plt.figure(figsize=(12, 6))
plt.plot(pc1_cum_scaled, label='PC1 Index (Scaled)', linewidth=1.5, color='blue')
plt.plot(vn30_cum_scaled, label='VN30 Index (Scaled)', linewidth=1.5, color='orange')

plt.title('So sánh xu hướng PC1 và VN30 Index', fontsize=14, fontweight='bold', pad=15)
plt.xlabel('Thời gian (Năm 2025 - 2026)')
plt.ylabel('Mức độ tăng trưởng tích lũy (Scaled)')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

# 7. Tính hệ số tương quan cuối cùng (sau khi có thể đã đảo dấu)
correlation_final = np.corrcoef(pc1_returns_series, vn30_returns)[0, 1]
print(f"\nCorrelation PC1 vs VN30: {correlation_final:.4f}")

# Reconstruct weights_pc1 and top3
# pc1_vector is already available from previous execution.
# standardized_stock_returns.columns is available from kernel state.
stock_columns = standardized_stock_returns.columns.tolist() # Ensure it's a list
weights_pc1 = pd.Series(pc1_vector, index=stock_columns)
top3 = weights_pc1.abs().sort_values(ascending=False).head(3).index.tolist()

# Phân loại mức correlation
if correlation_final > 0.8:
    level = "cao"
elif correlation_final > 0.5:
    level = "trung bình"
else:
    level = "thấp"

print("\n--- NHẬN XÉT Ý NGHĨA TÀI CHÍNH CỦA PC1 ---\n")

print(f"Hệ số tương quan giữa PC1 và VN30 là {correlation_final:.2f}, cho thấy mức độ liên hệ {level} giữa hai chuỗi.")

print(f"Các cổ phiếu có ảnh hưởng lớn nhất trong PC1 bao gồm: {', '.join(top3)}.")

print("PC1 đại diện cho yếu tố thị trường chung (market factor), phản ánh biến động tổng thể của các cổ phiếu trong rổ VN30.")

print("Khi PC1 tăng, phần lớn cổ phiếu có xu hướng tăng theo, cho thấy sự đồng biến của thị trường.")

"""## **Ý nghĩa tài chính của PC1**

### **1. Hệ số tương quan giữa PC1 và VN30-Index**
*   Hệ số tương quan giữa PC1 (Thành phần chính đầu tiên) và chỉ số VN30-Index là **0.93**.
*   Hệ số này cực kỳ cao, cho thấy PC1 và VN30-Index biến động gần như cùng chiều và có mối quan hệ tuyến tính rất mạnh.

### **2. Ý nghĩa tài chính của PC1**
*   **Đại diện cho Yếu tố thị trường chung (Market Factor):** Với hệ số tương quan cao như vậy, PC1 chính là **'nhịp đập'** của thị trường chứng khoán Việt Nam, đại diện cho xu hướng biến động tổng thể của các cổ phiếu trong rổ VN30. Nó loại bỏ các nhiễu động riêng lẻ của từng doanh nghiệp để giữ lại yếu tố rủi ro hệ thống chi phối.
*   **Cổ phiếu 'đầu tàu' (Market Leaders):** Các cổ phiếu có trọng số tuyệt đối lớn nhất trong PC1 là những mã có ảnh hưởng mạnh nhất đến sự biến động của yếu tố thị trường này. Dựa trên phân tích, các cổ phiếu như **TPB, ACB, TCB, VPB, CTG** nằm trong top đầu, cho thấy nhóm ngân hàng đóng vai trò dẫn dắt chính đối với xu hướng chung của VN30. Khi PC1 tăng (giảm), phần lớn các cổ phiếu này có xu hướng tăng (giảm) theo.
*   **Ứng dụng:** Việc hiểu PC1 giúp nhà đầu tư nắm bắt được xu hướng vĩ mô của thị trường, từ đó đưa ra các quyết định về phân bổ tài sản hoặc giao dịch theo xu hướng hiệu quả hơn.

## **6. Ý nghĩa tài chính của trọng số cổ phiếu**
"""

print("\n--- Phân tích Trọng số (Loadings) của PC1 (Ảnh hưởng đến Yếu tố Thị trường Chung) ---")

# Tạo DataFrame chứa trọng số PC1 của từng cổ phiếu
# pc1_vector chứa các trọng số, standardized_stock_returns.columns chứa tên cổ phiếu
loadings_df = pd.DataFrame({
    'Cổ phiếu': standardized_stock_returns.columns,
    'Trọng số (PC1 Loading)': pc1_vector,
    'Độ ảnh hưởng tuyệt đối': np.abs(pc1_vector)
})

# Sắp xếp theo độ ảnh hưởng tuyệt đối giảm dần để tìm các cổ phiếu 'dẫn dắt'
loadings_df_sorted = loadings_df.sort_values(by='Độ ảnh hưởng tuyệt đối', ascending=False)

print("\nTop 10 cổ phiếu có ảnh hưởng mạnh nhất đến PC1 (Yếu tố Thị trường Chung):")
display(loadings_df_sorted.head(10).style.background_gradient(cmap='Blues'))

print("\nTop 10 cổ phiếu có ảnh hưởng yếu nhất đến PC1 (Yếu tố Thị trường Chung):")
display(loadings_df_sorted.tail(10).style.background_gradient(cmap='Reds'))

# Visualize PC1 Loadings
plt.figure(figsize=(14, 7))
sns.barplot(x='Cổ phiếu', y='Trọng số (PC1 Loading)', data=loadings_df_sorted,
            palette='viridis', dodge=False, hue='Cổ phiếu', legend=False)
plt.title('Trọng số PC1 của từng cổ phiếu (Sắp xếp theo độ ảnh hưởng tuyệt đối)', fontsize=16)
plt.xlabel('Cổ phiếu', fontsize=12)
plt.ylabel('Trọng số PC1 (Loading)', fontsize=12)
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()

"""**Trọng số (Loadings) của PC1 là gì?**
Trong PCA, mỗi thành phần chính (PC) được tạo ra từ sự kết hợp tuyến tính của tất cả các biến ban đầu (30 cổ phiếu VN30). Trọng số (Loadings) chính là mức độ đóng góp của từng cổ phiếu vào PC1.
- Trọng số càng lớn (giá trị tuyệt đối càng cao) chứng tỏ cổ phiếu đó càng có ảnh hưởng mạnh đến biến động của PC1.
- Nếu PC1 thực sự đại diện cho "xu hướng thị trường chung" (Market Trend), thì các cổ phiếu có trọng số cao nhất trong PC1 chính là những cổ phiếu "dẫn dắt" thị trường.

**Phân tích nhóm ngành dẫn dắt thị trường (Sector Rotation/Leadership)**
Rổ VN30 bao gồm các doanh nghiệp hàng đầu thuộc nhiều lĩnh vực khác nhau. Dựa vào việc xếp hạng các cổ phiếu có trọng số cao nhất trong PC1, ta có thể rút ra những Insight tài chính cực kỳ đắt giá:

1. **Nhóm Ngân hàng (Bank):** Nếu các mã như VCB, BID, CTG, TCB... nằm trên top đầu của PC1, điều này hoàn toàn hợp lý với cấu trúc thị trường Việt Nam. Nhóm ngân hàng chiếm tỷ trọng vốn hóa rất lớn trong VN30, do đó, khi PC1 biến động, nhóm này đóng vai trò chi phối chủ đạo. Nhịp đập của "Market Trend" (PC1) gắn liền với sức khỏe ngành Ngân hàng.
2. **Nhóm Bất động sản (BĐS):** Các mã như VHM, VIC, VRE, KDH, NVL... cũng là những trụ cột lớn. Nếu nhóm này có Loading cao, điều đó cho thấy tâm lý thị trường đang bị ảnh hưởng mạnh bởi các chính sách, tin tức liên quan đến chu kỳ bất động sản, dòng vốn tín dụng hoặc trái phiếu.
3. **Nhóm Chứng khoán (SSI...):** Mặc dù số lượng ít trong VN30, nhưng nhóm chứng khoán được coi là "hàn thử biểu" cực nhạy của thị trường. Loading cao ở nhóm này phản ánh kỳ vọng của nhà đầu tư vào thanh khoản và sự sôi động chung của dòng tiền.
4. **Nhóm Bán lẻ, Sản xuất, Năng lượng (MWG, HPG, GAS...):** Nếu các nhóm ngành sản xuất và tiêu dùng cơ bản nổi lên đóng góp mạnh vào PC1, điều này có thể phản ánh một giai đoạn nền kinh tế thực đang phục hồi hoặc có những diễn biến vĩ mô đáng chú ý chi phối tâm lý chung.

Bằng cách trực quan hóa các Loadings này, chúng ta có thể nhìn thấy bức tranh tổng thể: "Thế lực" nào đang thực sự chèo lái con thuyền VN30!

# **KẾT LUẬN TỔNG KẾT PHẦN 2 & ỨNG DỤNG PCA VÀO THỰC TIỄN**

## **I. Tóm tắt các phát hiện chính từ Phân tích PCA trên rổ VN30**

1.  **PC1: Yếu tố Thị trường Chung (Market Factor)**
    *   **Giải thích Phương sai:** PC1 giải thích một phần lớn phương sai (khoảng **39.39%**) trong lợi suất của các cổ phiếu VN30, cho thấy sự tồn tại của một yếu tố chung mạnh mẽ tác động đến toàn thị trường.
    *   **Đồng pha với VN30-Index:** Hệ số tương quan cao (**~0.93**) giữa PC1 và chỉ số VN30-Index khẳng định PC1 là đại diện tin cậy cho "nhịp đập" tổng thể của thị trường Việt Nam.
    *   **Cổ phiếu dẫn dắt:** Các cổ phiếu có trọng số cao nhất trong PC1 (ví dụ: **TPB, ACB, TCB, VPB**) là những mã "đầu tàu" chi phối xu hướng thị trường chung, chủ yếu thuộc nhóm ngân hàng, phản ánh cấu trúc vốn hóa của VN30.

2.  **PC2 & PC3: Các Yếu tố Ngành (Sector Factors)**
    *   **Phân hóa ngành rõ rệt:** PCA đã xác định rõ các nhân tố ngành. PC2 thường đại diện cho sự đối trọng giữa nhóm Bất động sản (trọng số dương) và nhóm Năng lượng/Công nghiệp (trọng số âm).
    *   **Luân chuyển dòng tiền:** PC3 và các PC tiếp theo giải thích sự phân hóa hẹp hơn, phản ánh các giai đoạn luân chuyển dòng tiền giữa các nhóm ngành hoặc các nhóm cổ phiếu có đặc tính tài chính tương đồng.

3.  **Biểu đồ phân cụm (PC1 vs PC2)**
    *   **Tính đồng pha:** Biểu đồ này trực quan hóa rằng hầu hết các cổ phiếu VN30 đều có mối quan hệ đồng pha với PC1.
    *   **Cụm ngành:** Một cụm chặt chẽ của các mã ngân hàng cho thấy sự đồng pha nội bộ ngành rất cao. Các cổ phiếu khác như VIC, GAS, VJC, MWG thể hiện đặc tính độc lập hơn, ít nhạy cảm với sự luân chuyển dòng tiền chung.

## **II. Ứng dụng PCA vào Thực tiễn Đầu tư Chứng khoán**

Từ những phân tích trên, PCA mang lại những ứng dụng thực tiễn giá trị cho nhà đầu tư:

1.  **Giao dịch theo xu hướng (Trend Following với PC1):**
    *   Nhà đầu tư có thể sử dụng các cổ phiếu có trọng số lớn nhất trong PC1 (như TPB, ACB, TCB) làm **"chỉ báo sớm" (leading indicators)** cho xu hướng thị trường. Khi các mã này đồng loạt có dòng tiền vào mạnh hoặc có biến động tích cực, xác suất cao là thị trường chung (VN30) cũng sẽ có sóng tăng tương ứng.
    *   **Xác nhận xu hướng:** PC1 có thể dùng để xác nhận các tín hiệu xu hướng từ các chỉ báo kỹ thuật khác. Nếu PC1 tăng/giảm mạnh mẽ, nó củng cố cho giả thuyết về một xu hướng thị trường rõ ràng.

2.  **Giao dịch cặp / Luân chuyển dòng tiền (Pairs Trading & Sector Rotation với PC2/PC3):**
    *   **Phân bổ tài sản chiến lược:** Dựa trên các yếu tố ngành (PC2, PC3), nhà đầu tư có thể điều chỉnh tỷ trọng danh mục. Ví dụ, trong giai đoạn thị trường rủi ro cao (PC1 giảm), có thể giảm tỷ trọng ở các cụm ngành nhạy cảm (như Ngân hàng) và dịch chuyển vốn sang các cụm ngành độc lập hoặc phòng thủ (như một số mã Bán lẻ, Công nghệ, Năng lượng) để cân bằng rủi ro.
    *   **Chiến lược Pairs Trading:** Khi hai cổ phiếu hoặc hai nhóm ngành trong cùng một thành phần chính (ví dụ, PC2) có xu hướng lệch pha tạm thời (một tăng, một giảm), nhà đầu tư có thể thực hiện chiến lược mua cổ phiếu đang giảm giá và bán cổ phiếu đang tăng giá, kỳ vọng chúng sẽ quay trở lại trạng thái đồng pha ban đầu.
    *   **Nhận diện cơ hội:** Bằng cách theo dõi các biến động của PC2 và PC3, nhà đầu tư có thể nhận diện sớm các dấu hiệu luân chuyển dòng tiền giữa các nhóm ngành, từ đó đưa ra quyết định mua/bán tối ưu để tận dụng các "sóng ngành".

PCA không chỉ là một công cụ giảm chiều dữ liệu mà còn là một **"bộ lọc thông tin"** mạnh mẽ, giúp nhà đầu tư nhìn xuyên qua nhiễu động của từng cổ phiếu để hiểu rõ hơn về cấu trúc, xu hướng và sự phân hóa dòng tiền của thị trường.

# **CÁC CÂU HỎI NGHIÊN CỨU**


---

### **Q1: PC1 có thực sự đại diện cho chỉ số VN30 không?**

1. **Độ tương quan cực cao (0.9958):** Hệ số tương quan gần như bằng 1 giữa PC1 và chỉ số VN30 giả lập (trung bình cộng của rổ) cho thấy PC1 di chuyển gần như đồng nhất với xu hướng chung của rổ cổ phiếu.
2. **Tỷ lệ phương sai giải thích (33.16%):** Trong PCA tài chính, thành phần chính đầu tiên thường giải thích một phần lớn biến động của toàn bộ các cổ phiếu. Con số **33.16%** là mức điển hình cho thấy sự hiện diện của một 'Nhân tố thị trường' (Market Factor) chi phối.
3. **Trọng số đồng nhất:** Có thể thấy hầu hết các cổ phiếu trong rổ đều có trọng số dương trong PC1. Điều này có nghĩa là khi PC1 tăng, hầu hết các cổ phiếu trong VN30 đều tăng, phản ánh đúng tính chất của một chỉ số thị trường.
Kết luận: PC1 chính là 'nhịp đập' của thị trường VN30, loại bỏ các nhiễu riêng lẻ của từng doanh nghiệp để giữ lại xu hướng chung nhất.
"""

import seaborn as sns
import matplotlib.pyplot as plt

# So luong co phieu can ve
stocks = standardized_returns.columns
n_stocks = len(stocks)
cols = 5
rows = (n_stocks + cols - 1) // cols

fig, axes = plt.subplots(rows, cols, figsize=(20, 4 * rows))
axes = axes.flatten()

for i, stock in enumerate(stocks):
    sns.regplot(x=pc1_returns_series, y=standardized_returns[stock], ax=axes[i],
                scatter_kws={'alpha':0.3, 's':10}, line_kws={'color':'red'})
    axes[i].set_title(f'PC1 vs {stock}')
    axes[i].set_xlabel('PC1 Score')
    axes[i].set_ylabel('Returns')
    axes[i].set_ylim(standardized_returns[stock].min() * 1.2, standardized_returns[stock].max() * 1.2) # Adjusted limits
    axes[i].grid(True, alpha=0.2)

# An cac subplots thua
for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

"""### **Q2: Những cổ phiếu nào đóng vai trò 'đầu tàu' rủi ro hệ thống mạnh nhất?**

"""

# 1. Trich xuat trong so cua PC1 va sap xep theo thu tu giam dan
top_systemic_stocks = loadings_df_sorted[['Cổ phiếu', 'Trọng số (PC1 Loading)']].copy()

# 2. Dat ten lai cac cot de de hieu hon
top_systemic_stocks.columns = ['Ma Chung Khoan', 'Trong so PC1 (Do nhay thi truong)']

# 3. Hien thi Top 10 co phieu 'dau tau' rui ro he thong
print("Bảng: Top 10 mã chứng khoán nhạy cảm nhất với thị trường (Dựa trên PC1)")
display(top_systemic_stocks.head(10).style.background_gradient(cmap='YlOrRd'))

# 4. Nhan xet nhanh
top_1 = top_systemic_stocks.iloc[0]['Ma Chung Khoan']
print(f"\nNhan xet: {top_1} la co phieu nhay cam nhat. Khi PC1 (nhan to thi truong) bien dong 1 don vi, co phieu nay se phan ung manh nhat trong ro VN30.")

"""### **Q3: PC1, PC2 và PC3 đại diện cho yếu tố gì (Ngành hay đặc thù)?**

- **PC1 (Market Factor):** hầu hết các cổ phiếu đều có trọng số dương và khá đồng đều, đại diện cho xu hướng chung của thị trường.

- **PC2 (Real Estate vs. Energy/Industry):** Đây rõ ràng là một nhân tố phân hóa ngành.

    * **Phía dương (Positive):** Bị chi phối mạnh mẽ bởi nhóm Bất động sản họ Vingroup (VIC, VHM) và các mã BĐS khác như NVL, NLG.
    * **Phía âm (Negative):** Tập trung vào nhóm Năng lượng và Công nghiệp như PLX, GVR, GAS, POW.
**Ý nghĩa:** PC2 giải thích các giai đoạn mà nhóm Bất động sản biến động ngược chiều với nhóm Năng lượng/Sản xuất.
- **PC3 (Specific Sector Rotation):** Thường đại diện cho các vòng quay ngành hẹp hơn hoặc các nhóm cổ phiếu có đặc tính tài chính tương đồng (ví dụ: nhóm Ngân hàng đối trọng với nhóm Tiêu dùng).
"""

# Trích xuất trọng số của 3 PC đầu tiên
pc_weights = pd.DataFrame(
    sorted_eigenvectors[:, :3],
    index=standardized_stock_returns.columns, # Corrected index to match the number of eigenvectors
    columns=['PC1 (Market)', 'PC2 (Sector/Style)', 'PC3 (Sector/Style)']
)

# Trực quan hóa trọng số của 3 PC đầu tiên để tìm đặc trưng ngành
fig, axes = plt.subplots(3, 1, figsize=(15, 18))

for i, col in enumerate(pc_weights.columns):
    pc_weights[col].sort_values().plot(kind='bar', ax=axes[i],
                                      color=['red' if x < 0 else 'blue' for x in pc_weights[col].sort_values()])
    axes[i].set_title(f'Weights of stocks in {col}')
    axes[i].set_ylabel('Weight')
    axes[i].axhline(y=0, color='black', linestyle='-', alpha=0.3)

plt.tight_layout()
plt.show()

# Hiển thị các mã có trọng số tuyệt đối lớn nhất ở PC2 và PC3 để nhận diện ngành
print("Top stocks in PC2 (Positive vs Negative):")
display(pc_weights['PC2 (Sector/Style)'].sort_values(ascending=False).head(5))
display(pc_weights['PC2 (Sector/Style)'].sort_values(ascending=False).tail(5))

print("\nTop stocks in PC3 (Positive vs Negative):")
display(pc_weights['PC3 (Sector/Style)'].sort_values(ascending=False).head(5))
display(pc_weights['PC3 (Sector/Style)'].sort_values(ascending=False).tail(5))

"""### **Q4: Có tồn tại các “sector factors” trong VN30 không?**

Kết quả phân tích đã xác nhận có tồn tại các 'Sector Factors' (nhân tố ngành) rõ rệt trong chỉ số VN30:

- **PC2 (Nhân tố Bất động sản vs Năng lượng):** Ngành Bất động sản có trọng số dương cao nhất (0.21), trong khi ngành Năng lượng (-0.30) và Công nghiệp/Cao su (-0.37) có trọng số âm lớn nhất. Điều này chứng tỏ PC2 đại diện cho sự biến động trái chiều giữa hai nhóm này.
* **PC3 (Nhân tố luân chuyển tài chính):** Thành phần này cho thấy sự đối trọng giữa nhóm Năng lượng/Công nghiệp (Dương) và nhóm Ngân hàng/Chứng khoán (Âm).

* **PC1 (Nhân tố thị trường):** Tất cả các ngành đều có trọng số dương (từ 0.06 đến 0.24), củng cố kết luận PC1 là nhân tố chi phối toàn bộ thị trường.

Như vậy, cấu trúc thị trường Việt Nam không chỉ bị tác động bởi xu hướng chung mà còn bị phân hóa mạnh mẽ bởi các nhóm ngành đặc thù.
"""

# Khắc phục lỗi font hiển thị tiếng Việt trên Colab
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['axes.unicode_minus'] = False

# 1. Phân loại ngành thủ công cho rổ VN30 (Ước tính)
sector_map = {
    'ACB': 'Banking', 'BID': 'Banking', 'CTG': 'Banking', 'HDB': 'Banking',
    'MBB': 'Banking', 'SSB': 'Banking', 'STB': 'Banking', 'TCB': 'Banking',
    'TPB': 'Banking', 'VCB': 'Banking', 'VIB': 'Banking',
    'VIC': 'Real Estate', 'VHM': 'Real Estate', 'NVL': 'Real Estate',
    'PDR': 'Real Estate', 'KDH': 'Real Estate', 'NLG': 'Real Estate',
    'GAS': 'Energy', 'PLX': 'Energy', 'POW': 'Energy',
    'HPG': 'Steel/Industry', 'GVR': 'Industry/Rubber',
    'FPT': 'Technology', 'MSN': 'Consumer', 'VNM': 'Consumer',
    'MWG': 'Retail', 'VJC': 'Aviation', 'SBT': 'Agriculture',
    'SSI': 'Securities', 'BVH': 'Insurance'
}

# 2. Tạo DataFrame chứa trọng số và ngành
df_sectors = pc_weights.copy()
df_sectors['Sector'] = df_sectors.index.map(sector_map)

# 3. Tính toán trọng số trung bình theo ngành - numeric_only để tránh warning
sector_analysis = df_sectors.groupby('Sector').mean(numeric_only=True)

print("Trong so trung binh cua cac nganh tren cac thanh phan chinh:")
display(sector_analysis)

# 4. Trực quan hóa (Dùng tiếng Việt không dấu để tránh lỗi Glyph font)
plt.figure(figsize=(12, 8))
sns.heatmap(sector_analysis, annot=True, cmap='RdBu_r', center=0)
plt.title('Ma tran trong so trung binh theo nganh (Sector Loadings Analysis)')
plt.show()

# 5. Kết luận
print("\n--- KET LUAN ---")
print("Co ton tai cac 'Sector Factors' trong VN30:")
print("- PC2 dong vai tro ro ret la nhan to Bat dong san (Duong) doi trong voi Nang luong (Am).")
print("- PC3 thuong phan anh su dich chuyen giua nhom Ngan hang/Bao hiem va cac nganh khac.")

"""### **Q5: Phân tích nhóm ngành dẫn dắt bằng biểu đồ phân cụm (clustering)**"""

import plotly.graph_objects as go
import plotly.express as px
import pandas as pd

# ==========================================
# 1. BIỂU ĐỒ ROLLING CORRELATION (TƯƠNG QUAN TRƯỢT 30 NGÀY)
# ==========================================
rolling_corr = pc1_returns_series.rolling(window=30).corr(vn30_returns)

fig1 = go.Figure()
fig1.add_trace(go.Scatter(x=rolling_corr.index, y=rolling_corr, mode='lines',
                          name='Rolling 30-day Corr', line=dict(color='purple', width=2)))
fig1.update_layout(title="Độ ổn định của tương quan: Rolling Correlation (30 ngày) PC1 vs VN30",
                   xaxis_title="Thời gian", yaxis_title="Hệ số tương quan",
                   template="plotly_white", hovermode="x unified")
# Thêm đường tham chiếu 0.8
fig1.add_hline(y=0.8, line_dash="dash", line_color="green", annotation_text="Ngưỡng đồng pha cao (0.8)")
fig1.show()

# ==========================================
# 2. BẢN ĐỒ PHÂN CỤM CỔ PHIẾU (SCATTER 2D: PC1 VS PC2)
# ==========================================
# Trích xuất PC2
pc2_vector = sorted_eigenvectors[:, 1] # Use sorted_eigenvectors to get PC2

# Tạo DataFrame chứa Trọng số của PC1 và PC2
df_loadings = pd.DataFrame({
    'Cổ phiếu': standardized_stock_returns.columns, # Fixed: Use standardized_stock_returns.columns
    'PC1_Loading': pc1_vector,
    'PC2_Loading': pc2_vector
})

# Vẽ Scatter Plot
fig2 = px.scatter(df_loadings, x='PC1_Loading', y='PC2_Loading', text='Cổ phiếu',
                  title="Bản đồ Phân cụm Cổ phiếu VN30 (PCA Biplot: PC1 vs PC2)",
                  labels={'PC1_Loading': 'PC1 (Market Factor - Xu hướng thị trường)',
                          'PC2_Loading': 'PC2 (Sector Rotation - Phân hóa dòng tiền)'},
                  template="plotly_white", size_max=12)

# Căn chỉnh text và trục tọa độ
fig2.update_traces(textposition='top center', marker=dict(size=9, color='red', opacity=0.7))
fig2.add_hline(y=0, line_width=1, line_dash="dash", line_color="gray")
fig2.add_vline(x=0, line_width=1, line_dash="dash", line_color="gray")
fig2.show()

"""*(Các biểu đồ trong phần này được xây dựng bằng thư viện Interactive Plotly. Thầy có thể **rê chuột (hover)** trực tiếp vào các đường đồ thị hoặc các chấm tròn để xem chi tiết ngày giao dịch, tên cổ phiếu và thông số cụ thể. Có thể dùng chuột khoanh vùng kéo thả để **phóng to (zoom)** các cụm cổ phiếu nằm sát nhau).*

**ĐÁNH GIÁ VÀ NHẬN XÉT:**

**1. Về độ ổn định của tương quan (Rolling Correlation 30 ngày):**
* Nhìn chung, hệ số tương quan trượt giữa PC1 và VN30 phần lớn thời gian đều neo ở mức rất cao (trên ngưỡng 0.8). Điều này khẳng định vững chắc kết luận: PC1 là một chỉ báo đại diện cực kỳ ổn định cho xu hướng thị trường xuyên suốt chu kỳ.
* Tuy nhiên, hệ thống thỉnh thoảng ghi nhận những **"khoảng trũng" (nhịp sụt giảm tương quan đột ngột)**. Về mặt tài chính, đây chính là tín hiệu của các giai đoạn thị trường chịu cú sốc ngắn hạn (tin tức vĩ mô xấu, hoảng loạn bán tháo). Lúc này, dòng tiền phản ứng hỗn loạn khiến các cổ phiếu tạm thời đứt gãy tính đồng pha vốn có với thị trường chung.

**2. Về Bản đồ phân cụm (Sự luân chuyển dòng tiền - PC2):**
Nếu PC1 (Trục X) đại diện cho rủi ro hệ thống thì Thành phần chính thứ 2 (PC2 - Trục Y) chính là lăng kính để quan sát sự phân hóa giữa các nhóm ngành. Cấu trúc "hình phễu" của dữ liệu nói lên 3 đặc điểm cốt lõi:
* **Tính đồng pha tuyệt đối (Trục X):** Toàn bộ 30 mã đều bị ép về nửa âm của Trục X (PC1 < 0). Điều này hoàn toàn trùng khớp với kết quả Loadings ở phần 2.4, minh chứng toán học cho việc cả rổ VN30 đang đi chung một nhịp đập thị trường.
* **Sự gom cụm của Ngân hàng (Góc trái):** Khi phóng to và rê chuột vào cụm dữ liệu dày đặc ở góc tận cùng bên trái (PC1 quanh -0.23, PC2 quanh 0), hệ thống chỉ điểm toàn bộ là các mã Ngân hàng (TPB, ACB, TCB, MBB...). Sự dính chặt này chứng tỏ dòng tiền đổ vào nhóm Bank mang tính bầy đàn (đồng pha nội bộ ngành) rất cao.
* **Sự phân hóa độc lập (Góc phải xòe ra):** Ở vùng PC1 tiến gần về 0, các điểm dữ liệu phân tán rất rộng lên/xuống theo trục dọc PC2. Rê chuột vào đây sẽ thấy các đại diện như VIC, GAS, VJC, MWG. Cấu trúc này tố cáo chúng là những cổ phiếu có "câu chuyện kinh doanh" độc lập, phòng thủ, và ít nhạy cảm với pha luân chuyển dòng tiền chung.

=> **Kết luận:** Mô hình PCA không chỉ xuất sắc trong việc nén chiều dữ liệu (PC1) mà còn là một bộ lọc (filter) sắc bén để nhà đầu tư phân lớp danh mục và nhận diện cấu trúc dòng tiền (PC2).
"""